### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by a819411321** [yjn870/WDSR-pytorch#1]
[epoch: 1/300]
lr: : 0it [00:00, ?it/s]
train:   0%|          | 0/16000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/WDSR-pytorch-master/train.py", line 160, in <module>
    train_loss = train(train_dataset, train_dataloader, model, criterion, optimizer, tag='train')
  File "D:/WDSR-pytorch-master/train.py", line 44, in train
    for batch,data in loader:
  File "D:\python3.6.5\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "D:\python3.6.5\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "D:\\python3.6.5\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "D:\\python3.6.5\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "D:\\WDSR-pytorch-master\\core\\data\\div2k.py", line 77, in __getitem__\n    lr, hr = get_patch(h5[\'lr\'][idx], h5[\'hr\'][idx], self.args.patch_size, self.args.scale,\n  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "D:\\python3.6.5\\lib\\site-packages\\h5py\\_hl\\group.py", line 262, in __getitem__\n    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "h5py\\h5o.pyx", line 190, in h5py.h5o.open\nKeyError: "Unable to open object (object \'223\' doesn\'t exist)"\n'

Process finished with exit code 1

error in train.py   line 44 for data in loader:

**Comment by BastianChen** [comment]
> [epoch: 1/300]
> lr: : 0it [00:00, ?it/s]
> train: 0%| | 0/16000 [00:00<?, ?it/s]
> Traceback (most recent call last):
> File "D:/WDSR-pytorch-master/train.py", line 160, in
> train_loss = train(train_dataset, train_dataloader, model, criterion, optimizer, tag='train')
> File "D:/WDSR-pytorch-master/train.py", line 44, in train
> for batch,data in loader:
> File "D:\python3.6.5\lib\site-packages\torch\utils\data\dataloader.py", line 637, in **next**
> return self._process_next_batch(batch)
> File "D:\python3.6.5\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> KeyError: 'Traceback (most recent call last):\n File "D:\python3.6.5\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop\n samples = collate_fn([dataset[i] for i in batch_indices])\n File "D:\python3.6.5\lib\site-packages\torch\utils\data\dataloader.py", line 138, in \n samples = collate_fn([dataset[i] for i in batch_indices])\n File "D:\WDSR-pytorch-master\core\data\div2k.py", line 77, in **getitem**\n lr, hr = get_patch(h5['lr'][idx], h5['hr'][idx], self.args.patch_size, self.args.scale,\n File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n File "D:\python3.6.5\lib\site-packages\h5py\_hl\group.py", line 262, in **getitem**\n oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n File "h5py\h5o.pyx", line 190, in h5py.h5o.open\nKeyError: "Unable to open object (object '223' doesn't exist)"\n'
> 
> Process finished with exit code 1
> 
> error in train.py line 44 for data in loader:

I meet the same error,do you resolve it?

**Comment by bozliu** [comment]
I met the same error too
